# tools/gen-agents.ps1 - regenerates the junior/senior agent files in .claude/agents from each role's mid file.
# Example: powershell -NoProfile -ExecutionPolicy Bypass -File tools/gen-agents.ps1
# For every <role>-junior-*.md and <role>-senior-*.md it keeps that file's own name, description, model and effort,
# copies tools:, skills: and mcpServers: plus the whole body from <role>-mid-*.md, and prepends one level paragraph.
# Edit the mid file, then rerun this. Idempotent: files whose content would not change are left untouched.
param([switch]$Check)  # -Check: write nothing, exit 1 if any file is out of date
$ErrorActionPreference = 'Stop'
$repo = Split-Path -Parent $PSScriptRoot
$agentsDir = Join-Path $repo '.claude/agents'
$midNote = '<!-- The junior/senior copies of this agent are generated from this file by tools/gen-agents.ps1: edit here, then rerun it. -->'

function Split-Agent([string]$path) {
    $lines = (Get-Content -LiteralPath $path -Raw -Encoding UTF8) -replace "`r`n", "`n" -split "`n"
    if ($lines[0] -ne '---') { throw "No frontmatter in $path" }
    $end = [Array]::IndexOf($lines, '---', 1)
    if ($end -lt 0) { throw "Unclosed frontmatter in $path" }
    # Frontmatter keys -> their full text (a key line plus any indented continuation lines).
    $keys = [ordered]@{}
    $cur = $null
    foreach ($l in $lines[1..($end - 1)]) {
        if ($l -match '^([A-Za-z][\w-]*):') { $cur = $Matches[1]; $keys[$cur] = $l }
        elseif ($cur) { $keys[$cur] += "`n" + $l }
    }
    $body = if ($end + 1 -le $lines.Count - 1) { $lines[($end + 1)..($lines.Count - 1)] -join "`n" } else { '' }
    return @{ Keys = $keys; Body = $body.TrimEnd("`n") }
}

$levelText = @{
    junior = 'Keep to the brief. If the task turns out bigger or riskier than described (unclear cause, new design needed, touches architecture or networking), stop and report back so the lead can hand it to a senior; don''t improvise a large change.'
    senior = 'You own the hard parts: think through the design before building, weigh alternatives, look for edge cases and failure modes, and leave the result documented so mid and junior agents can extend it. Mentor through your report: note the patterns others should follow.'
}

$changed = @()
$files = Get-ChildItem -LiteralPath $agentsDir -Filter '*.md' | Where-Object { $_.BaseName -match '^(.+)-(junior|senior)-[a-z]+$' } | Sort-Object Name
foreach ($f in $files) {
    $null = $f.BaseName -match '^(.+)-(junior|senior)-[a-z]+$'
    $role = $Matches[1]; $level = $Matches[2]
    $mids = @(Get-ChildItem -LiteralPath $agentsDir -Filter "$role-mid-*.md")
    if ($mids.Count -ne 1) { throw "Expected exactly one mid file for role '$role', found $($mids.Count)" }
    $mid = Split-Agent $mids[0].FullName
    $own = Split-Agent $f.FullName

    $fm = @('---')
    foreach ($k in 'name', 'description') { if (-not $own.Keys.Contains($k)) { throw "$($f.Name) has no $k" }; $fm += $own.Keys[$k] }
    foreach ($k in 'tools', 'skills', 'mcpServers') { if ($mid.Keys.Contains($k)) { $fm += $mid.Keys[$k] } }
    foreach ($k in 'model', 'effort') { if ($own.Keys.Contains($k)) { $fm += $own.Keys[$k] } }
    $fm += '---'

    $midBody = $mid.Body -split "`n"
    if ($midBody[0] -eq $midNote) { $midBody = $midBody[1..($midBody.Count - 1)] }
    $gen = "<!-- GENERATED by tools/gen-agents.ps1 from $($mids[0].Name): edit that file, then rerun the script. -->"
    $intro = "You are a $level $role on Lure. $($levelText[$level])"
    $text = (($fm + $gen + $intro + '' + $midBody) -join "`n").TrimEnd("`n") + "`n"

    $old = (Get-Content -LiteralPath $f.FullName -Raw -Encoding UTF8) -replace "`r`n", "`n"
    if ($old -ne $text) {
        $changed += $f.Name
        if (-not $Check) { [IO.File]::WriteAllText($f.FullName, $text, (New-Object Text.UTF8Encoding($false))) }
    }
}
if ($Check) {
    if ($changed.Count) { Write-Output ("Out of date: " + ($changed -join ', ')); exit 1 }
    Write-Output "All $($files.Count) generated agent files are up to date."; exit 0
}
Write-Output ("Generated $($files.Count) agent files; changed: " + $(if ($changed.Count) { $changed -join ', ' } else { 'none' }))
